[package]
name = "crop_insurance1"
version = "1.0.0"
authors = []

[addresses]
crop_insurance1 = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
